<?php
declare(strict_types=1);

namespace App\Service;

use App\Service\Branding\BrandingImageException;
use App\Service\Branding\IcoWriter;
use Cake\Core\Configure;
use Cake\ORM\Locator\LocatorAwareTrait;
use GdImage;
use Psr\Http\Message\UploadedFileInterface;
use Throwable;

/**
 * The site's logo and favicon.
 *
 * Both live on disk under webroot/img/branding, never in the database. They are
 * on every single page, including the public scoreboard players leave open all
 * day, so they have to be served by the web server straight from a file the way
 * any other static asset is, without a PHP request or a blob read behind them.
 *
 * The `config` table therefore stores only a choice: the slug of one of the
 * shipped presets, or `custom` for artwork an administrator uploaded. Uploads
 * are re-encoded rather than moved into place, so the file that ends up in
 * webroot is always one GD produced from pixels it could actually decode.
 */
class BrandingService
{
    use LocatorAwareTrait;

    /**
     * `config` row holding the chosen logo.
     */
    public const PARAM_LOGO = 'brand_logo';

    /**
     * `config` row holding the chosen favicon.
     */
    public const PARAM_FAVICON = 'brand_favicon';

    /**
     * The slug that means "use the artwork an administrator uploaded".
     */
    public const CUSTOM = 'custom';

    /**
     * Fallback whenever the stored choice is missing or no longer exists.
     */
    public const DEFAULT_SLUG = 'dragon-crest';

    /**
     * Formats an administrator may upload, and what each is served as.
     *
     * The type is decided by decoding the file, never by the browser's
     * Content-Type header, which the client controls.
     *
     * @var array<int, string>
     */
    public const ALLOWED_TYPES = [
        IMAGETYPE_PNG => 'image/png',
        IMAGETYPE_JPEG => 'image/jpeg',
        IMAGETYPE_GIF => 'image/gif',
        IMAGETYPE_WEBP => 'image/webp',
    ];

    /**
     * Logo rules. The navbar scales the image to about 33 pixels tall and lets
     * it keep its own width, so anything from a square emblem to a fairly wide
     * wordmark works; something taller than it is wide does not.
     */
    public const LOGO_MIN_SIDE = 128;
    public const LOGO_MAX_SIDE = 2048;
    public const LOGO_MAX_BYTES = 2097152;
    public const LOGO_MIN_RATIO = 0.8;
    public const LOGO_MAX_RATIO = 3.0;

    /**
     * The size the stored logo is normalised to, on its longest side.
     */
    public const LOGO_STORED_SIDE = 512;

    /**
     * Favicon rules. A favicon is drawn at 16 pixels more often than not, so it
     * has to be square and it has to start out big enough that the downscale to
     * 16 still leaves something readable.
     */
    public const FAVICON_MIN_SIDE = 32;
    public const FAVICON_MAX_SIDE = 512;
    public const FAVICON_MAX_BYTES = 524288;

    /**
     * How far from square a favicon may be, as a fraction of its own width.
     *
     * Not zero: exporting a 64x63 icon from a drawing tool is a rounding
     * accident, not a different intention, and it is squared up on save.
     */
    public const FAVICON_RATIO_TOLERANCE = 0.1;

    /**
     * The square side the stored favicon PNG is normalised to.
     */
    public const FAVICON_STORED_SIDE = 256;

    /**
     * The shipped artwork, in the order the picker shows it.
     *
     * Every slug here has a directory of the same name under
     * webroot/img/branding/presets holding logo.png, favicon.png and
     * favicon.ico, all generated by `bin/cake branding_presets`.
     *
     * @var array<string, array{label: string, blurb: string}>
     */
    public const PRESETS = [
        'dragon-crest' => [
            'label' => 'Dragon Crest',
            'blurb' => 'A horned wyrm over a crimson field.',
        ],
        'crossed-swords' => [
            'label' => 'Crossed Swords',
            'blurb' => 'Two blades crossed on burnished steel.',
        ],
        'knight-helm' => [
            'label' => 'Knight\'s Helm',
            'blurb' => 'A closed great helm, visor down.',
        ],
        'castle-keep' => [
            'label' => 'Castle Keep',
            'blurb' => 'The three towers of the stronghold.',
        ],
        'war-axe' => [
            'label' => 'War Axe',
            'blurb' => 'A double-bladed axe on a dark field.',
        ],
        'dragon-claw' => [
            'label' => 'Dragon Claw',
            'blurb' => 'Three talons closing on the field.',
        ],
        'ogre-skull' => [
            'label' => 'Ogre Skull',
            'blurb' => 'The horned skull of a slain monster.',
        ],
        'crown-of-war' => [
            'label' => 'Crown of War',
            'blurb' => 'A crown above crossed daggers.',
        ],
        'tower-shield' => [
            'label' => 'Tower Shield',
            'blurb' => 'A studded shield bearing the cross.',
        ],
        'war-banner' => [
            'label' => 'War Banner',
            'blurb' => 'A pennant flying from a raised spear.',
        ],
    ];

    /**
     * Absolute path of the directory holding every branding file.
     *
     * Normally a directory inside webroot, because the web server has to be
     * able to serve these files itself. `Branding.root` overrides it so that a
     * test can write artwork somewhere disposable instead of over the real
     * site's.
     *
     * @return string Path with a trailing separator.
     */
    public static function root(): string
    {
        $configured = Configure::read('Branding.root');
        if (is_string($configured) && $configured !== '') {
            return rtrim($configured, '\/') . DS;
        }

        return WWW_ROOT . 'img' . DS . 'branding' . DS;
    }

    /**
     * Where the copy of the chosen icon that browsers ask for by name lives.
     *
     * @return string
     */
    private static function rootFaviconPath(): string
    {
        $configured = Configure::read('Branding.root');
        if (is_string($configured) && $configured !== '') {
            return rtrim($configured, '\/') . DS . 'favicon.ico';
        }

        return WWW_ROOT . 'favicon.ico';
    }

    /**
     * Absolute path of the directory holding one slug's files.
     *
     * @param string $slug A preset slug, or `custom`.
     * @return string Path with a trailing separator.
     */
    public static function directoryFor(string $slug): string
    {
        if ($slug === self::CUSTOM) {
            return self::root() . self::CUSTOM . DS;
        }

        return self::root() . 'presets' . DS . $slug . DS;
    }

    /**
     * Web path of the directory holding one slug's files.
     *
     * @param string $slug A preset slug, or `custom`.
     * @return string Path with a trailing slash.
     */
    public static function urlFor(string $slug): string
    {
        if ($slug === self::CUSTOM) {
            return '/img/branding/custom/';
        }

        return '/img/branding/presets/' . $slug . '/';
    }

    /**
     * Whether a slug names one of the shipped presets.
     *
     * @param string $slug The slug to check.
     * @return bool
     */
    public static function isPreset(string $slug): bool
    {
        return array_key_exists($slug, self::PRESETS);
    }

    /**
     * The slug currently chosen for the logo, guaranteed to have files on disk.
     *
     * @return string
     */
    public function logoSlug(): string
    {
        return $this->resolve(self::PARAM_LOGO, 'logo.png');
    }

    /**
     * The slug currently chosen for the favicon, guaranteed to have files on disk.
     *
     * @return string
     */
    public function faviconSlug(): string
    {
        return $this->resolve(self::PARAM_FAVICON, 'favicon.ico');
    }

    /**
     * URL of the logo to put in the navbar, with a cache-busting stamp.
     *
     * @return string
     */
    public function logoUrl(): string
    {
        $slug = $this->logoSlug();

        return $this->stamp(self::urlFor($slug) . 'logo.png', self::directoryFor($slug) . 'logo.png');
    }

    /**
     * The `<link rel="icon">` targets for the chosen favicon.
     *
     * Both forms are emitted when both exist: the .ico so that anything old
     * enough to want one finds it, and the PNG because every current browser
     * prefers it and picks it when it is offered.
     *
     * @return list<array{href: string, type: string, sizes: string}>
     */
    public function faviconLinks(): array
    {
        $slug = $this->faviconSlug();
        $directory = self::directoryFor($slug);
        $url = self::urlFor($slug);

        $links = [];
        if (is_file($directory . 'favicon.ico')) {
            $links[] = [
                'href' => $this->stamp($url . 'favicon.ico', $directory . 'favicon.ico'),
                'type' => 'image/x-icon',
                'sizes' => 'any',
            ];
        }
        if (is_file($directory . 'favicon.png')) {
            $links[] = [
                'href' => $this->stamp($url . 'favicon.png', $directory . 'favicon.png'),
                'type' => 'image/png',
                'sizes' => self::FAVICON_STORED_SIDE . 'x' . self::FAVICON_STORED_SIDE,
            ];
        }

        return $links;
    }

    /**
     * URL of the image that best represents a slug in the picker.
     *
     * @param string $slug A preset slug, or `custom`.
     * @param string $kind Either `logo` or `favicon`.
     * @return string|null Null when that slug has no such artwork on disk.
     */
    public function previewUrl(string $slug, string $kind = 'logo'): ?string
    {
        $directory = self::directoryFor($slug);
        $candidates = $kind === 'favicon'
            ? ['favicon.png', 'favicon.ico']
            : ['logo.png'];

        foreach ($candidates as $file) {
            if (is_file($directory . $file)) {
                return $this->stamp(self::urlFor($slug) . $file, $directory . $file);
            }
        }

        return null;
    }

    /**
     * Whether an administrator has uploaded artwork of their own.
     *
     * @param string $kind Either `logo` or `favicon`.
     * @return bool
     */
    public function hasCustom(string $kind): bool
    {
        $directory = self::directoryFor(self::CUSTOM);

        if ($kind === 'favicon') {
            return is_file($directory . 'favicon.ico');
        }

        return is_file($directory . 'logo.png');
    }

    /**
     * Choose which artwork the site uses for its logo.
     *
     * @param string $slug A preset slug, or `custom`.
     * @return void
     * @throws \App\Service\Branding\BrandingImageException When that artwork is not on disk.
     */
    public function selectLogo(string $slug): void
    {
        $this->assertAvailable($slug, 'logo.png', __('That logo is not available.'));
        $this->write(
            self::PARAM_LOGO,
            $slug,
            'Logo shown in the navbar. A preset slug, or "custom" for an uploaded image.'
        );
    }

    /**
     * Choose which artwork the site uses for its favicon.
     *
     * @param string $slug A preset slug, or `custom`.
     * @return void
     * @throws \App\Service\Branding\BrandingImageException When that artwork is not on disk.
     */
    public function selectFavicon(string $slug): void
    {
        $this->assertAvailable($slug, 'favicon.ico', __('That favicon is not available.'));
        $this->write(
            self::PARAM_FAVICON,
            $slug,
            'Browser tab icon. A preset slug, or "custom" for an uploaded image.'
        );
        $this->publishRootFavicon($slug);
    }

    /**
     * Accept an uploaded logo, re-encode it and put it on disk.
     *
     * Selecting it is left to the caller: an upload that replaces the file the
     * site is already pointing at should not also silently change the choice.
     *
     * @param \Psr\Http\Message\UploadedFileInterface $file The upload.
     * @return void
     * @throws \App\Service\Branding\BrandingImageException When the file breaks one of the rules.
     */
    public function storeCustomLogo(UploadedFileInterface $file): void
    {
        $bytes = $this->readUpload($file, self::LOGO_MAX_BYTES);
        [$width, $height] = $this->measure($bytes);

        if ($width < self::LOGO_MIN_SIDE || $height < self::LOGO_MIN_SIDE) {
            throw new BrandingImageException(__(
                'The logo is too small: it is {0}x{1} and the minimum is {2}x{2} pixels.',
                $width,
                $height,
                self::LOGO_MIN_SIDE
            ));
        }

        if ($width > self::LOGO_MAX_SIDE || $height > self::LOGO_MAX_SIDE) {
            throw new BrandingImageException(__(
                'The logo is too large: it is {0}x{1} and the maximum is {2}x{2} pixels.',
                $width,
                $height,
                self::LOGO_MAX_SIDE
            ));
        }

        $ratio = $width / $height;
        if ($ratio < self::LOGO_MIN_RATIO || $ratio > self::LOGO_MAX_RATIO) {
            throw new BrandingImageException(__(
                'The logo is the wrong shape: it is {0}x{1}. Use a square emblem, or anything up to '
                . '{2} times wider than it is tall.',
                $width,
                $height,
                (int)self::LOGO_MAX_RATIO
            ));
        }

        $image = $this->decode($bytes);
        try {
            // Longest side to a fixed length: the navbar and the picker both
            // scale it anyway, and a bounded file is what keeps a 2048px
            // upload from being re-sent to every visitor on every page.
            $scale = self::LOGO_STORED_SIDE / max($width, $height);
            $resized = $this->resample(
                $image,
                max(1, (int)round($width * $scale)),
                max(1, (int)round($height * $scale))
            );

            try {
                $directory = self::directoryFor(self::CUSTOM);
                $this->makeDirectory($directory);
                $this->savePng($resized, $directory . 'logo.png');
            } finally {
                imagedestroy($resized);
            }
        } finally {
            imagedestroy($image);
        }
    }

    /**
     * Accept an uploaded favicon, re-encode it and put it on disk.
     *
     * A raster upload is squared up, stored as a PNG and turned into a
     * multi-resolution .ico. An .ico upload is kept as it is: it already holds
     * sizes somebody chose deliberately, and GD cannot open it to do better.
     *
     * @param \Psr\Http\Message\UploadedFileInterface $file The upload.
     * @return void
     * @throws \App\Service\Branding\BrandingImageException When the file breaks one of the rules.
     */
    public function storeCustomFavicon(UploadedFileInterface $file): void
    {
        $bytes = $this->readUpload($file, self::FAVICON_MAX_BYTES);
        $directory = self::directoryFor(self::CUSTOM);

        $icoSize = IcoWriter::readLargestSize($bytes);
        if ($icoSize !== null) {
            $this->assertFaviconDimensions($icoSize[0], $icoSize[1]);
            $this->makeDirectory($directory);
            $this->put($directory . 'favicon.ico', $bytes);
            // An .ico cannot be re-encoded to PNG here, so any PNG left behind
            // by an earlier upload has to go: otherwise the layout would go on
            // pointing the browser at the previous icon.
            if (is_file($directory . 'favicon.png')) {
                @unlink($directory . 'favicon.png');
            }
            $this->afterFaviconWrite();

            return;
        }

        [$width, $height] = $this->measure($bytes);
        $this->assertFaviconDimensions($width, $height);

        $image = $this->decode($bytes);
        try {
            $square = $this->resample($image, self::FAVICON_STORED_SIDE, self::FAVICON_STORED_SIDE);
            try {
                $this->makeDirectory($directory);
                $this->savePng($square, $directory . 'favicon.png');
                $this->put($directory . 'favicon.ico', IcoWriter::fromImage($square));
            } finally {
                imagedestroy($square);
            }
        } finally {
            imagedestroy($image);
        }

        $this->afterFaviconWrite();
    }

    /**
     * Copy the chosen icon to webroot/favicon.ico.
     *
     * Browsers, feed readers and link unfurlers ask for /favicon.ico by name
     * without looking at the page first, so the root file has to be kept in
     * step with the choice rather than left as whatever shipped.
     *
     * @param string|null $slug The chosen slug, or null to re-read it.
     * @return bool Whether the root file now matches the choice.
     */
    public function publishRootFavicon(?string $slug = null): bool
    {
        $slug ??= $this->faviconSlug();
        $source = self::directoryFor($slug) . 'favicon.ico';
        if (!is_file($source)) {
            return false;
        }

        $target = self::rootFaviconPath();
        // A deployment that keeps webroot read-only is a legitimate setup, and
        // the <link> tags still point at the right file, so this is a nicety
        // that must never take the page down with it.
        if (file_exists($target) && !is_writable($target)) {
            return false;
        }

        return @copy($source, $target);
    }

    /**
     * Read the stored choice, falling back when it names artwork that is gone.
     *
     * @param string $param The `config` row to read.
     * @param string $required The file that has to exist for the choice to stand.
     * @return string
     */
    private function resolve(string $param, string $required): string
    {
        $slug = $this->read($param);

        if (
            $slug !== null
            && ($slug === self::CUSTOM || self::isPreset($slug))
            && is_file(self::directoryFor($slug) . $required)
        ) {
            return $slug;
        }

        return self::DEFAULT_SLUG;
    }

    /**
     * Read one `config` value.
     *
     * Degrades to null rather than throwing: this runs while the layout is
     * being rendered, which also happens for the error page shown when the
     * database is the thing that is broken.
     *
     * @param string $param The row to read.
     * @return string|null
     */
    private function read(string $param): ?string
    {
        try {
            $row = $this->fetchTable('Config')->find()->where(['param' => $param])->first();
        } catch (Throwable $e) {
            return null;
        }

        $value = $row->value ?? null;

        return is_string($value) && $value !== '' ? $value : null;
    }

    /**
     * Write one `config` value, creating the row if this install predates it.
     *
     * @param string $param The row to write.
     * @param string $value The new value.
     * @param string $description Description used only when the row is created.
     * @return void
     */
    private function write(string $param, string $value, string $description): void
    {
        $table = $this->fetchTable('Config');
        $row = $table->find()->where(['param' => $param])->first();

        if ($row === null) {
            $row = $table->newEmptyEntity();
            $row->set('param', $param);
            $row->set('description', $description);
        }

        $row->set('value', $value);
        $table->saveOrFail($row);
    }

    /**
     * Refuse a choice whose artwork is not on disk.
     *
     * @param string $slug The slug being chosen.
     * @param string $required The file it needs.
     * @param string $message What to say when it is missing.
     * @return void
     * @throws \App\Service\Branding\BrandingImageException
     */
    private function assertAvailable(string $slug, string $required, string $message): void
    {
        $known = $slug === self::CUSTOM || self::isPreset($slug);
        if (!$known || !is_file(self::directoryFor($slug) . $required)) {
            throw new BrandingImageException($message);
        }
    }

    /**
     * Check that an icon is square enough to be used as one.
     *
     * @param int $width Width in pixels.
     * @param int $height Height in pixels.
     * @return void
     * @throws \App\Service\Branding\BrandingImageException
     */
    private function assertFaviconDimensions(int $width, int $height): void
    {
        if ($width < self::FAVICON_MIN_SIDE || $height < self::FAVICON_MIN_SIDE) {
            throw new BrandingImageException(__(
                'The favicon is too small: it is {0}x{1} and the minimum is {2}x{2} pixels.',
                $width,
                $height,
                self::FAVICON_MIN_SIDE
            ));
        }

        if ($width > self::FAVICON_MAX_SIDE || $height > self::FAVICON_MAX_SIDE) {
            throw new BrandingImageException(__(
                'The favicon is too large: it is {0}x{1} and the maximum is {2}x{2} pixels.',
                $width,
                $height,
                self::FAVICON_MAX_SIDE
            ));
        }

        if (abs($width - $height) > $width * self::FAVICON_RATIO_TOLERANCE) {
            throw new BrandingImageException(__(
                'The favicon must be square: this one is {0}x{1} pixels.',
                $width,
                $height
            ));
        }
    }

    /**
     * Pull the bytes out of an upload and check the things that do not need a
     * decoder: that it arrived, that it is not empty, that it is not oversized.
     *
     * @param \Psr\Http\Message\UploadedFileInterface $file The upload.
     * @param int $maxBytes The ceiling for this kind of image.
     * @return string
     * @throws \App\Service\Branding\BrandingImageException
     */
    private function readUpload(UploadedFileInterface $file, int $maxBytes): string
    {
        if ($file->getError() === UPLOAD_ERR_INI_SIZE || $file->getError() === UPLOAD_ERR_FORM_SIZE) {
            throw new BrandingImageException(__(
                'The file is too large. The limit is {0} KB.',
                (int)round($maxBytes / 1024)
            ));
        }

        if ($file->getError() !== UPLOAD_ERR_OK) {
            throw new BrandingImageException(__('The file could not be uploaded. Please, try again.'));
        }

        $size = $file->getSize();
        if ($size !== null && $size > $maxBytes) {
            throw new BrandingImageException(__(
                'The file is too large: it is {0} KB and the limit is {1} KB.',
                (int)round($size / 1024),
                (int)round($maxBytes / 1024)
            ));
        }

        $bytes = (string)$file->getStream();
        if ($bytes === '') {
            throw new BrandingImageException(__('The file is empty.'));
        }

        if (strlen($bytes) > $maxBytes) {
            throw new BrandingImageException(__(
                'The file is too large: it is {0} KB and the limit is {1} KB.',
                (int)round(strlen($bytes) / 1024),
                (int)round($maxBytes / 1024)
            ));
        }

        return $bytes;
    }

    /**
     * Read the dimensions of an image whose format we accept.
     *
     * @param string $bytes The raw file.
     * @return array{0: int, 1: int} Width and height.
     * @throws \App\Service\Branding\BrandingImageException When it is not an image we take.
     */
    private function measure(string $bytes): array
    {
        // Silenced deliberately: the bytes came from an upload, so a file that
        // is not an image at all is an expected input, not a programming error.
        $info = @getimagesizefromstring($bytes);
        if ($info === false || !isset(self::ALLOWED_TYPES[$info[2]])) {
            throw new BrandingImageException(__('Use a PNG, JPEG, GIF or WebP image.'));
        }

        return [(int)$info[0], (int)$info[1]];
    }

    /**
     * Decode an already-measured image.
     *
     * @param string $bytes The raw file.
     * @return \GdImage
     * @throws \App\Service\Branding\BrandingImageException When the pixels are unreadable.
     */
    private function decode(string $bytes): GdImage
    {
        $image = @imagecreatefromstring($bytes);
        if ($image === false) {
            throw new BrandingImageException(__('The image could not be read. It may be damaged.'));
        }

        return $image;
    }

    /**
     * Scale an image onto a transparent canvas of the given size.
     *
     * @param \GdImage $source The decoded upload.
     * @param int $width Target width.
     * @param int $height Target height.
     * @return \GdImage
     */
    private function resample(GdImage $source, int $width, int $height): GdImage
    {
        $canvas = imagecreatetruecolor($width, $height);
        imagealphablending($canvas, false);
        imagesavealpha($canvas, true);
        imagefill($canvas, 0, 0, (int)imagecolorallocatealpha($canvas, 0, 0, 0, 127));
        imagecopyresampled(
            $canvas,
            $source,
            0,
            0,
            0,
            0,
            $width,
            $height,
            imagesx($source),
            imagesy($source)
        );

        return $canvas;
    }

    /**
     * Write a PNG, keeping its alpha channel.
     *
     * @param \GdImage $image The image to write.
     * @param string $path Absolute destination path.
     * @return void
     * @throws \App\Service\Branding\BrandingImageException When the file cannot be written.
     */
    private function savePng(GdImage $image, string $path): void
    {
        imagesavealpha($image, true);

        ob_start();
        $ok = imagepng($image, null, 9);
        $bytes = (string)ob_get_clean();

        if (!$ok || $bytes === '') {
            throw new BrandingImageException(__('The image could not be converted. Please, try another file.'));
        }

        $this->put($path, $bytes);
    }

    /**
     * Write a file, or say why it could not be written.
     *
     * @param string $path Absolute destination path.
     * @param string $bytes The contents.
     * @return void
     * @throws \App\Service\Branding\BrandingImageException When the write fails.
     */
    private function put(string $path, string $bytes): void
    {
        if (@file_put_contents($path, $bytes) === false) {
            throw new BrandingImageException(__(
                'The image could not be saved to disk. Check that {0} is writable by the web server.',
                dirname($path)
            ));
        }
    }

    /**
     * Create a directory if it is not already there.
     *
     * @param string $path Absolute directory path.
     * @return void
     * @throws \App\Service\Branding\BrandingImageException When it cannot be created.
     */
    private function makeDirectory(string $path): void
    {
        if (is_dir($path)) {
            return;
        }

        if (!@mkdir($path, 0755, true) && !is_dir($path)) {
            throw new BrandingImageException(__(
                'The folder {0} could not be created. Check the permissions of the webroot directory.',
                $path
            ));
        }
    }

    /**
     * Keep webroot/favicon.ico in step after custom artwork is replaced.
     *
     * @return void
     */
    private function afterFaviconWrite(): void
    {
        if ($this->faviconSlug() === self::CUSTOM) {
            $this->publishRootFavicon(self::CUSTOM);
        }
    }

    /**
     * Append the file's modification time to its URL.
     *
     * Preset files never change, but a custom logo is replaced in place under a
     * fixed name, and without this the browser would go on showing the previous
     * one until its cache expired.
     *
     * @param string $url The web path.
     * @param string $path The file behind it.
     * @return string
     */
    private function stamp(string $url, string $path): string
    {
        $time = @filemtime($path);

        return $time === false ? $url : $url . '?v=' . $time;
    }
}
