name: Deploy via Git (SSH)
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy to Server via SSH and Git
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASS }}
        script: |
          TARGET_DIR="/home/storage/4/ab/f9/k201/public_html"
          REPO_URL="https://github.com/crashbrtb/chestcounter.git"
          BRANCH="main"

          echo "Accessing directory $TARGET_DIR"
          cd "$TARGET_DIR" || exit 1

          # Verificar se é um repositório Git. Se não, clonar.
          if [ ! -d ".git" ]; then
            echo "Directory is not a Git repository. Cloning $REPO_URL branch $BRANCH..."
            # Certifique-se de que o diretório está vazio ou o clone falhará
            # Você pode querer adicionar `rm -rf ./* ./.[!.]*` aqui com MUITO CUIDADO se souber que pode limpar
            git clone --branch "$BRANCH" "$REPO_URL" .
            if [ $? -ne 0 ]; then
              echo "Failed to clone repository."
              exit 1
            fi
            echo "Repository cloned successfully."
          else
            echo "Directory is a Git repository. Updating..."
            echo "Checking git status before update..."
            git status
            
            echo "Updating repository with $BRANCH branch..."
            git fetch origin "$BRANCH"
            git reset --hard "origin/$BRANCH"
            git clean -fdx # Remove untracked files and directories
            echo "Repository updated."
          fi

          echo "Configuring app_local.php on server..."
          if [ -f config/app_local.example.php ]; then
            cp config/app_local.example.php config/app_local.php
            echo "Copied app_local.example.php to app_local.php on server"

            # Substituir placeholders no app_local.php
            sed -i "s#'salt' => env('SECURITY_SALT', '__SALT__'),#'salt' => '${{ secrets.SECURITY_SALT_PROD }}',#g" config/app_local.php
            sed -i "s#'host' => 'localhost',#'host' => '${{ secrets.DB_HOST_PROD }}',#g" config/app_local.php
            sed -i "s#'username' => 'my_app',#'username' => '${{ secrets.DB_USER_PROD }}',#g" config/app_local.php
            sed -i "s#'password' => 'secret',#'password' => '${{ secrets.DB_PASSWORD_PROD }}',#g" config/app_local.php
            sed -i "s#'database' => 'my_app',#'database' => '${{ secrets.DB_NAME_PROD }}',#g" config/app_local.php
            
            echo "app_local.php configured with production secrets on server."
          else
            echo "ERROR: config/app_local.example.php not found on server! This usually means the git clone/pull failed or the file is missing in the repository."
            # Considerar sair com erro se o arquivo de config for essencial
            # exit 1 
          fi

          echo "Checking git status after update and config..."
          git status
          echo "Deploy completed successfully!!"
